#! /bin/bash

BASHRC_SSH_AGENT_CONFIG=".bashrc_sshagent"
BASHRC_GIT_COLOR_CONFIG=".bashrc_gitcolor"


if [ -f "${BASHRC_SSH_AGENT_CONFIG}" ]
then
    source "${BASHRC_SSH_AGENT_CONFIG}"
fi

if [ -f "${BASHRC_GIT_COLOR_CONFIG}" ]
then
    source "${BASHRC_GIT_COLOR_CONFIG}"
fi
