#! /bin/bash

# Configure colors, if available.
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  C_RESET='\[\e[0m\]'
  C_USER='\[\e[1;33m\]'
  C_PATH='\[\e[0;33m\]'
  C_GIT_CLEAN='\[\e[0;36m\]'
  C_GIT_DIRTY='\[\e[0;35m\]'
else
  C_RESET=
  C_USER=
  C_PATH=
  C_GIT_CLEAN=
  C_GIT_DIRTY=
fi

# Function to assemble the Git parsingart of our prompt.
git_prompt ()
{
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    return 0
  fi

  git_branch=$(git branch 2>/dev/null | sed -n '/^\*/s/^\* //p')

  if git diff --quiet 2>/dev/null >&2; then
    GIT_COLOR="${C_GIT_CLEAN}"
  else
    GIT_COLOR="${C_GIT_DIRTY}"
  fi

  echo "[${GIT_COLOR}$git_branch${C_RESET}]"
}

# Thy holy prompt.
PROMPT_COMMAND='PS1="${C_USER}\u${C_RESET}@${C_USER}\h${C_RESET}:${C_PATH}\w${C_RESET}$(git_prompt)\$ "'